# Generated by Django 5.2.5 on 2026-01-02 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome da Tarefa"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descricao"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Saude"),
                            ("studies", "Estudos"),
                            ("spiritual", "Espiritual"),
                            ("exercise", "Exercicio Fisico"),
                            ("nutrition", "Nutricao"),
                            ("meditation", "Meditacao"),
                            ("reading", "Leitura"),
                            ("writing", "Escrita"),
                            ("work", "Trabalho"),
                            ("leisure", "Lazer"),
                            ("family", "Familia"),
                            ("social", "Social"),
                            ("finance", "Financas"),
                            ("household", "Casa"),
                            ("personal_care", "Cuidado Pessoal"),
                            ("other", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Periodicidade",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terca-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sabado"),
                            (6, "Domingo"),
                        ],
                        help_text="Apenas para tarefas semanais (0=Segunda, 6=Domingo)",
                        null=True,
                        verbose_name="Dia da Semana",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Apenas para tarefas mensais (1-31)",
                        null=True,
                        verbose_name="Dia do Mes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Tarefa Ativa"),
                ),
                (
                    "target_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Ex: 8 copos de agua, 30 minutos de leitura",
                        verbose_name="Quantidade Alvo",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="vez",
                        help_text="Ex: copos, minutos, paginas, vezes",
                        max_length=50,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routine_tasks",
                        to="members.member",
                        verbose_name="Proprietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa Rotineira",
                "verbose_name_plural": "Tarefas Rotineiras",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titulo do Objetivo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descricao"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("consecutive_days", "Dias Consecutivos"),
                            ("total_days", "Total de Dias"),
                            ("avoid_habit", "Evitar Habito"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Objetivo",
                    ),
                ),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        help_text="Ex: 15 dias, 100 vezes, etc", verbose_name="Meta"
                    ),
                ),
                (
                    "current_value",
                    models.PositiveIntegerField(default=0, verbose_name="Valor Atual"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data de Inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusao"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("completed", "Concluido"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goals",
                        to="members.member",
                        verbose_name="Proprietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: vincular objetivo a uma tarefa rotineira",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="personal_planning.routinetask",
                        verbose_name="Tarefa Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo",
                "verbose_name_plural": "Objetivos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Cumprida"),
                ),
                (
                    "quantity_completed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quanto foi realizado (ex: 6 de 8 copos de agua)",
                        verbose_name="Quantidade Realizada",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observacoes"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Conclusao"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_task_records",
                        to="members.member",
                        verbose_name="Proprietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_records",
                        to="personal_planning.routinetask",
                        verbose_name="Tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Diario de Tarefa",
                "verbose_name_plural": "Registros Diarios de Tarefas",
                "ordering": ["-date", "task__category"],
            },
        ),
        migrations.CreateModel(
            name="DailyReflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("reflection", models.TextField(verbose_name="Reflexao do Dia")),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Bom"),
                            ("neutral", "Neutro"),
                            ("bad", "Ruim"),
                            ("terrible", "Pessimo"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Humor do Dia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_reflections",
                        to="members.member",
                        verbose_name="Proprietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflexao Diaria",
                "verbose_name_plural": "Reflexoes Diarias",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-date"], name="personal_pl_owner_i_0bdb02_idx"
                    )
                ],
                "unique_together": {("date", "owner")},
            },
        ),
        migrations.AddIndex(
            model_name="routinetask",
            index=models.Index(
                fields=["owner", "is_active"], name="personal_pl_owner_i_d45170_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routinetask",
            index=models.Index(
                fields=["periodicity", "is_active"],
                name="personal_pl_periodi_1d0067_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["owner", "status"], name="personal_pl_owner_i_d9d73d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["status", "-created_at"], name="personal_pl_status_d4a52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskrecord",
            index=models.Index(
                fields=["owner", "-date"], name="personal_pl_owner_i_95f061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskrecord",
            index=models.Index(
                fields=["task", "-date"], name="personal_pl_task_id_041315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailytaskrecord",
            index=models.Index(
                fields=["completed", "-date"], name="personal_pl_complet_d9dfad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailytaskrecord",
            unique_together={("task", "date", "owner")},
        ),
    ]
