# Generated by Django 5.2.5 on 2026-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinetask",
            name="custom_month_days",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Array de dias do mês [1-31] para periodicidade personalizada",
                null=True,
                verbose_name="Dias do Mês Personalizados",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="custom_weekdays",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Array de dias da semana [0-6] para periodicidade personalizada",
                null=True,
                verbose_name="Dias da Semana Personalizados",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="interval_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A cada X dias (para periodicidade personalizada)",
                null=True,
                verbose_name="Intervalo em Dias",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="interval_start_date",
            field=models.DateField(
                blank=True,
                help_text="Data de referência para calcular intervalos",
                null=True,
                verbose_name="Data de Início do Intervalo",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="times_per_month",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantas vezes por mês (para periodicidade personalizada)",
                null=True,
                verbose_name="Vezes por Mês",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="times_per_week",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantas vezes por semana (para periodicidade personalizada)",
                null=True,
                verbose_name="Vezes por Semana",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreflection",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excelente"),
                    ("good", "Bom"),
                    ("neutral", "Neutro"),
                    ("bad", "Ruim"),
                    ("terrible", "Péssimo"),
                ],
                max_length=20,
                null=True,
                verbose_name="Humor do Dia",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("consecutive_days", "Dias Consecutivos"),
                    ("total_days", "Total de Dias"),
                    ("avoid_habit", "Evitar Hábito"),
                    ("custom", "Personalizado"),
                ],
                max_length=30,
                verbose_name="Tipo de Objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("cancelled", "Cancelado"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="routinetask",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "Saúde"),
                    ("studies", "Estudos"),
                    ("spiritual", "Espiritual"),
                    ("exercise", "Exercício Físico"),
                    ("nutrition", "Nutrição"),
                    ("meditation", "Meditação"),
                    ("reading", "Leitura"),
                    ("writing", "Escrita"),
                    ("work", "Trabalho"),
                    ("leisure", "Lazer"),
                    ("family", "Família"),
                    ("social", "Social"),
                    ("finance", "Finanças"),
                    ("household", "Casa"),
                    ("personal_care", "Cuidado Pessoal"),
                    ("other", "Outros"),
                ],
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="routinetask",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Diária"),
                    ("weekdays", "Dias Úteis"),
                    ("weekly", "Semanal"),
                    ("monthly", "Mensal"),
                    ("custom", "Personalizado"),
                ],
                default="daily",
                max_length=20,
                verbose_name="Periodicidade",
            ),
        ),
        migrations.AlterField(
            model_name="routinetask",
            name="weekday",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Segunda-feira"),
                    (1, "Terça-feira"),
                    (2, "Quarta-feira"),
                    (3, "Quinta-feira"),
                    (4, "Sexta-feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                help_text="Apenas para tarefas semanais (0=Segunda, 6=Domingo)",
                null=True,
                verbose_name="Dia da Semana",
            ),
        ),
    ]
