# Generated by Django 5.2.5 on 2026-01-09 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("personal_planning", "0002_routinetask_custom_month_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routinetask",
            name="daily_occurrences",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantas vezes a tarefa deve ser feita por dia",
                verbose_name="Ocorrências por Dia",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="default_time",
            field=models.TimeField(
                blank=True,
                help_text="Horário padrão para esta tarefa",
                null=True,
                verbose_name="Horário Padrão",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="interval_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Intervalo em horas entre cada ocorrência intradiária",
                null=True,
                verbose_name="Intervalo entre Repetições (horas)",
            ),
        ),
        migrations.AddField(
            model_name="routinetask",
            name="scheduled_times",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Lista de horários específicos ["08:00", "14:00", "20:00"]',
                null=True,
                verbose_name="Horários Programados",
            ),
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="Nome da Tarefa"),
                ),
                (
                    "task_description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Saúde"),
                            ("studies", "Estudos"),
                            ("spiritual", "Espiritual"),
                            ("exercise", "Exercício Físico"),
                            ("nutrition", "Nutrição"),
                            ("meditation", "Meditação"),
                            ("reading", "Leitura"),
                            ("writing", "Escrita"),
                            ("work", "Trabalho"),
                            ("leisure", "Lazer"),
                            ("family", "Família"),
                            ("social", "Social"),
                            ("finance", "Finanças"),
                            ("household", "Casa"),
                            ("personal_care", "Cuidado Pessoal"),
                            ("other", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data Programada")),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário Programado"
                    ),
                ),
                (
                    "occurrence_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Para tarefas com múltiplas ocorrências no dia (0-based)",
                        verbose_name="Índice da Ocorrência",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Andamento"),
                            ("completed", "Concluída"),
                            ("skipped", "Pulada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade Alvo"
                    ),
                ),
                (
                    "quantity_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Realizada"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="vez", max_length=50, verbose_name="Unidade"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciada em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluída em"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_instances",
                        to="members.member",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="personal_planning.routinetask",
                        verbose_name="Tarefa Modelo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instância de Tarefa",
                "verbose_name_plural": "Instâncias de Tarefas",
                "ordering": ["scheduled_date", "scheduled_time", "occurrence_index"],
                "indexes": [
                    models.Index(
                        fields=["owner", "scheduled_date"],
                        name="personal_pl_owner_i_cbf3be_idx",
                    ),
                    models.Index(
                        fields=["template", "scheduled_date"],
                        name="personal_pl_templat_90c6eb_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_date"],
                        name="personal_pl_status_889955_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date", "scheduled_time"],
                        name="personal_pl_schedul_ef821c_idx",
                    ),
                ],
                "unique_together": {
                    ("template", "scheduled_date", "occurrence_index", "owner")
                },
            },
        ),
    ]
