# Generated by Django - Migration de dados DailyTaskRecord → TaskInstance

from django.db import migrations
from django.utils import timezone


def migrate_records_to_instances(apps, schema_editor):
    """
    Migra DailyTaskRecord existentes para TaskInstance.

    Lógica:
    - Para cada DailyTaskRecord, cria TaskInstance(s) baseado em quantity_completed
    - Se quantity_completed > 0, cria instâncias com status='completed'
    - Se completed=False mas quantity_completed > 0, cria instâncias parciais
    - Cada unidade do target_quantity gera uma instância separada
    """
    DailyTaskRecord = apps.get_model('personal_planning', 'DailyTaskRecord')
    TaskInstance = apps.get_model('personal_planning', 'TaskInstance')
    RoutineTask = apps.get_model('personal_planning', 'RoutineTask')

    migrated_count = 0
    skipped_count = 0

    for record in DailyTaskRecord.objects.filter(deleted_at__isnull=True):
        try:
            task = record.task
            if not task:
                skipped_count += 1
                continue

            # Determina quantas instâncias criar baseado no target_quantity
            num_instances = task.target_quantity if task.target_quantity > 0 else 1

            for i in range(num_instances):
                # Verifica se já existe uma instância para este índice
                existing = TaskInstance.objects.filter(
                    template=task,
                    scheduled_date=record.date,
                    occurrence_index=i,
                    owner=record.owner
                ).exists()

                if existing:
                    continue

                # Determina o status baseado na quantidade completada
                if i < record.quantity_completed:
                    status = 'completed'
                    completed_at = record.completed_at or timezone.now()
                elif record.quantity_completed > 0 and i == record.quantity_completed:
                    # Próxima tarefa não completada fica como 'in_progress'
                    status = 'in_progress'
                    completed_at = None
                else:
                    status = 'pending'
                    completed_at = None

                TaskInstance.objects.create(
                    template=task,
                    task_name=task.name,
                    task_description=task.description,
                    category=task.category,
                    scheduled_date=record.date,
                    scheduled_time=None,  # Dados legados não têm horário
                    occurrence_index=i,
                    status=status,
                    target_quantity=1,  # Cada instância representa 1 unidade
                    quantity_completed=1 if status == 'completed' else 0,
                    unit=task.unit,
                    notes=record.notes if i == 0 else None,  # Notas apenas na primeira instância
                    completed_at=completed_at,
                    owner=record.owner,
                    created_by=record.created_by,
                    updated_by=record.updated_by,
                    created_at=record.created_at,
                    updated_at=record.updated_at,
                )
                migrated_count += 1

        except Exception as e:
            print(f"Erro ao migrar DailyTaskRecord {record.id}: {e}")
            skipped_count += 1
            continue

    print(f"Migração concluída: {migrated_count} instâncias criadas, {skipped_count} registros ignorados")


def reverse_migration(apps, schema_editor):
    """
    Reverte a migração removendo instâncias criadas automaticamente.

    Nota: Esta reversão remove TODAS as TaskInstances que têm um template associado.
    Instâncias avulsas (sem template) não são afetadas.
    """
    TaskInstance = apps.get_model('personal_planning', 'TaskInstance')

    # Remove apenas instâncias que foram geradas a partir de templates
    deleted_count = TaskInstance.objects.filter(
        template__isnull=False
    ).delete()[0]

    print(f"Reversão concluída: {deleted_count} instâncias removidas")


class Migration(migrations.Migration):

    dependencies = [
        ('personal_planning', '0003_add_task_instance_model'),
    ]

    operations = [
        migrations.RunPython(migrate_records_to_instances, reverse_migration),
    ]
