# Generated by Django 5.2.5 on 2026-01-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal_planning", "0004_migrate_daily_records_to_instances"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyTaskRecord",
        ),
    ]
