# Generated by Django 5.2.5 on 2026-01-02 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("members", "0001_initial"),
        ("revenues", "0001_initial"),
        ("transfers", "0003_alter_transfered_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="related_transfer",
            field=models.ForeignKey(
                blank=True,
                help_text="Transferência que gerou esta receita automaticamente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_revenue",
                to="transfers.transfer",
                verbose_name="Transferência Relacionada",
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=models.Index(
                fields=["related_transfer"], name="revenues_re_related_4e3839_idx"
            ),
        ),
    ]
