# Generated by Django 5.2.5 on 2026-01-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("loans", "0001_initial"),
        ("members", "0001_initial"),
        ("revenues", "0002_revenue_related_transfer_and_more"),
        ("transfers", "0004_link_existing_transfer_transactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="related_loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Empréstimo que esta receita está recebendo (quando você emprestou e está recebendo de volta)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_revenues",
                to="loans.loan",
                verbose_name="Empréstimo Relacionado",
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=models.Index(
                fields=["related_loan"], name="revenues_re_related_ce0fa8_idx"
            ),
        ),
    ]
