# Generated by Django 5.2.5 on 2026-02-06 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('notification_type', models.CharField(choices=[('task_today', 'Tarefa do Dia'), ('task_overdue', 'Tarefa Atrasada'), ('payable_due_soon', 'Valor a Pagar Próximo do Vencimento'), ('payable_overdue', 'Valor a Pagar Atrasado'), ('loan_due_soon', 'Empréstimo Próximo do Vencimento'), ('loan_overdue', 'Empréstimo Atrasado'), ('bill_due_soon', 'Fatura Próxima do Vencimento'), ('bill_overdue', 'Fatura Atrasada')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('content_type', models.CharField(max_length=50, verbose_name='Tipo de Conteúdo')),
                ('object_id', models.IntegerField(verbose_name='ID do Objeto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.member', verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_read'], name='notificatio_owner_i_52bdcd_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
                'unique_together': {('owner', 'notification_type', 'content_type', 'object_id')},
            },
        ),
    ]
