# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_institution_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='overdraft_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Limite máximo de débito negativo permitido na conta', max_digits=15, verbose_name='Limite de Cheque Especial'),
        ),
    ]
