# Generated by Django 5.2.5 on 2026-01-20 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('date', models.DateField(verbose_name='Data de Registro')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('category', models.CharField(choices=[('food and drink', 'Comida e bebida'), ('bills and services', 'Contas e serviços'), ('electronics', 'Eletrônicos'), ('family and friends', 'Amizades e Família'), ('pets', 'Animais de estimação'), ('digital signs', 'Assinaturas digitais'), ('house', 'Casa'), ('purchases', 'Compras'), ('donate', 'Doações'), ('education', 'Educação'), ('loans', 'Empréstimos'), ('entertainment', 'Entretenimento'), ('taxes', 'Impostos'), ('investments', 'Investimentos'), ('others', 'Outros'), ('vestuary', 'Roupas'), ('health and care', 'Saúde e cuidados pessoais'), ('professional services', 'Serviços profissionais'), ('supermarket', 'Supermercado'), ('rates', 'Taxas'), ('transport', 'Transporte'), ('travels', 'Viagens')], max_length=200, verbose_name='Categoria')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paid', 'Quitado'), ('overdue', 'Em atraso'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member', verbose_name='Membro Responsável')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Valor a Pagar',
                'verbose_name_plural': 'Valores a Pagar',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='payables_pa_date_a89508_idx'), models.Index(fields=['status', '-date'], name='payables_pa_status_8a828c_idx'), models.Index(fields=['category', '-date'], name='payables_pa_categor_5b27fc_idx')],
            },
        ),
    ]
