# Generated by Django 5.2.5 on 2026-01-02 13:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("expenses", "0003_expense_related_transfer_and_more"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "default_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Padrão"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food and drink", "Comida e bebida"),
                            ("bills and services", "Contas e serviços"),
                            ("electronics", "Eletrônicos"),
                            ("family and friends", "Amizades e Família"),
                            ("pets", "Animais de estimação"),
                            ("digital signs", "Assinaturas digitais"),
                            ("house", "Casa"),
                            ("purchases", "Compras"),
                            ("donate", "Doações"),
                            ("education", "Educação"),
                            ("loans", "Empréstimos"),
                            ("entertainment", "Entretenimento"),
                            ("taxes", "Impostos"),
                            ("investments", "Investimentos"),
                            ("others", "Outros"),
                            ("vestuary", "Roupas"),
                            ("health and care", "Saúde e cuidados pessoais"),
                            ("professional services", "Serviços profissionais"),
                            ("supermarket", "Supermercado"),
                            ("rates", "Taxas"),
                            ("transport", "Transporte"),
                            ("travels", "Viagens"),
                        ],
                        max_length=200,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "due_day",
                    models.PositiveIntegerField(
                        help_text="Dia do mês em que a despesa vence (1-31)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia de Vencimento",
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Estabelecimento",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Dinheiro"),
                            ("debit_card", "Cartão de Débito"),
                            ("credit_card", "Cartão de Crédito"),
                            ("pix", "PIX"),
                            ("transfer", "Transferência"),
                            ("check", "Cheque"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para desativar sem excluir",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "allow_value_edit",
                    models.BooleanField(
                        default=True,
                        help_text="Permite ajustar o valor ao lançar a despesa",
                        verbose_name="Permitir Editar Valor",
                    ),
                ),
                (
                    "last_generated_month",
                    models.CharField(
                        blank=True,
                        help_text="Formato: YYYY-MM",
                        max_length=7,
                        null=True,
                        verbose_name="Último Mês Gerado",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                        verbose_name="Membro Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Fixa",
                "verbose_name_plural": "Despesas Fixas",
                "ordering": ["due_day", "description"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="fixed_expense_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template de despesa fixa que gerou esta despesa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_expenses",
                to="expenses.fixedexpense",
                verbose_name="Modelo de Despesa Fixa",
            ),
        ),
        migrations.CreateModel(
            name="FixedExpenseGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Formato: YYYY-MM",
                        max_length=7,
                        unique=True,
                        verbose_name="Mês",
                    ),
                ),
                (
                    "total_generated",
                    models.PositiveIntegerField(default=0, verbose_name="Total Gerado"),
                ),
                (
                    "fixed_expense_ids",
                    models.JSONField(
                        default=list,
                        help_text="Lista de IDs dos templates que foram gerados",
                        verbose_name="IDs das Despesas Fixas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado Por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Geração",
                "verbose_name_plural": "Logs de Geração",
                "ordering": ["-month"],
            },
        ),
        migrations.AddIndex(
            model_name="fixedexpense",
            index=models.Index(
                fields=["account", "is_active"], name="expenses_fi_account_e994cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedexpense",
            index=models.Index(
                fields=["due_day", "is_active"], name="expenses_fi_due_day_4bf680_idx"
            ),
        ),
    ]
