# Generated by Django 5.2.5 on 2026-01-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_institution_unique"),
        ("expenses", "0004_add_fixed_expense_feature"),
        ("loans", "0001_initial"),
        ("members", "0001_initial"),
        ("transfers", "0004_link_existing_transfer_transactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="related_loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Empréstimo que esta despesa está pagando (quando você deve e está pagando)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_expenses",
                to="loans.loan",
                verbose_name="Empréstimo Relacionado",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["related_loan"], name="expenses_ex_related_518343_idx"
            ),
        ),
    ]
