# Generated by Django 5.2.5 on 2026-01-20 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_overdraft_limit'),
        ('credit_cards', '0005_migrate_expenses_to_purchases'),
        ('expenses', '0008_expense_related_bill_payment_and_more'),
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        ('payables', '0001_initial'),
        ('transfers', '0004_link_existing_transfer_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_payable',
            field=models.ForeignKey(blank=True, help_text='Valor a pagar que esta despesa está abatendo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_expenses', to='payables.payable', verbose_name='Valor a Pagar Relacionado'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['related_payable'], name='expenses_ex_related_b5237b_idx'),
        ),
    ]
