# Generated by Django 5.2.5 on 2026-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0002_alter_creditcard__security_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcardexpense",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor"
            ),
        ),
    ]
