# Generated by Django 5.2.5 on 2026-02-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0005_migrate_expenses_to_purchases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCardExpense',
        ),
    ]
