# Generated by Django 5.2.5 on 2026-01-09 08:52

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type: expense, book, password, goal, etc.",
                        max_length=100,
                        verbose_name="Tipo de Entidade",
                    ),
                ),
                (
                    "content_id",
                    models.PositiveIntegerField(verbose_name="ID da Entidade"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento Pessoal"),
                            ("seguranca", "Seguranca"),
                            ("financeiro", "Financeiro"),
                            ("leitura", "Leitura/Biblioteca"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "sensibilidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        db_index=True,
                        default="baixa",
                        max_length=10,
                        verbose_name="Sensibilidade",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Searchable tags for filtering",
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Reference date (expense date, reading date, etc.)",
                        null=True,
                        verbose_name="Data de Referencia",
                    ),
                ),
                (
                    "texto_original",
                    models.TextField(
                        help_text="Human-readable text for display",
                        verbose_name="Texto Original",
                    ),
                ),
                (
                    "texto_busca",
                    models.TextField(
                        help_text="Optimized text for embedding generation",
                        verbose_name="Texto para Busca",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        null=True,
                        verbose_name="Vetor de Embedding",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Entity-specific metadata for rich search results",
                        verbose_name="Metadados Adicionais",
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Indexado"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Indexacao"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="nomic-embed-text",
                        max_length=100,
                        verbose_name="Modelo de Embedding",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_embeddings",
                        to="members.member",
                        verbose_name="Proprietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Conteudo",
                "verbose_name_plural": "Embeddings de Conteudo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "tipo"], name="idx_owner_tipo"),
                    models.Index(
                        fields=["owner", "sensibilidade"], name="idx_owner_sens"
                    ),
                    models.Index(
                        fields=["owner", "is_indexed"], name="idx_owner_indexed"
                    ),
                    models.Index(
                        fields=["content_type", "content_id"], name="idx_content_ref"
                    ),
                    models.Index(
                        fields=["owner", "-data_referencia"], name="idx_owner_data"
                    ),
                ],
                "unique_together": {("content_type", "content_id", "owner")},
            },
        ),
    ]
